name: jacoco-to-gsheet
description: 'Adds jacoco code coverage report to the Google spreadsheet'
inputs:
  SPREADSHEET_ID:
    description: The id(alphanumeric value that is between the /d/ and the /edit in the URL of your spreadsheet) of the spreadsheet that needs to be updated. 
    required: true
  JACOCO_CSV_PATH:
    description: Path to the jacoco csv report.
    required: true
  SPREADSHEET_NAME:
    description: Name of the spreadsheet where the report will be stored.
    required: true
  API_PRIVATE_KEY:
    description: Private key to access the Google sheets API.
    required: true
  API_CLIENT_EMAIL:
    description: Email that will be used to edit the Google sheets API.
    required: true
outputs:
  SPREADSHEETSHEET_LINK:
    description: Link for the updated google sheet
runs:
  using: node12
  main: dist/index.js
