name: Build Distribution
on: [push]
    branches:
      - master
jobs:
  build-distribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build node js module
        uses: gps/ncc-gha@master
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
